apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment-2
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: helloworld-deployment-2
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: helloworld-deployment-2
    spec:
      volumes:
        - name: www-content
          emptyDir:
            sizeLimit: 5Mi
      containers:
        - name: hello-world
          image: helloworld-webserver:2.0.0
          volumeMounts:
            - mountPath: /www
              name: www-content
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
        - name: get-content-sidecar
          image: get-content:1.0.0
          volumeMounts:
            - mountPath: /www
              name: www-content
          command:
            - bash
            - -c
            - |
              git clone https://github.com/gambinodaniele/k8s-sidecars.git /www2
              cd /www2
              while true; do
                date
                git pull
                ls -al
                cp -p ./docker/www/* /www
                sleep 60
              done
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
