apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    app: my-nginx
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  # Note here that we match both the app and the version
  selector:
    app.kubernetes.io/name: helloworld-deployment-1
